HO DB Repair Tool

* Build

  To build:

  #+begin_src bash
./mvnw package
  #+end_src

* Release

  #+begin_src bash
mvn -Dresume=false release:prepare release:perform -Pgithub -Prelease -Dtoken=<GITHUB_TOKEN>
  #+end_src

* Usage

** Repair

   The repair tool makes a best effort to:

   - Read an existing database into memory: this phase may throw
     errors depending on the state of the database.  In particular
     some of the tables may be corrupted.
   - Apply transformations for some known issues,
   - Dump the transformed data to SQL files on disk,
   - Re-import data into a new database with a target version.

   #+begin_src bash
$ ./bin/hodb-repair -d ~/tmp/database -o /tmp/output/database -v 3.0.0
Exporting db /home/sebastien/tmp/database to new db at /tmp/output/database with version 3.0.0...

...  possible errors ...

Loading file /tmp/USERCOLUMNS.sql...
Loading file /tmp/FINANZEN.sql...
Loading file /tmp/MATCHSUBSTITUTION.sql...
Loading file /tmp/HT_WORLDDETAILS.sql...
Loading file /tmp/LIGA.sql...
Loading file /tmp/IFA_MATCHES.sql...
Loading file /tmp/FAKTOREN.sql...
Loading file /tmp/AUFSTELLUNG.sql...
Loading file /tmp/SPIELERSKILLUP.sql...
Loading file /tmp/STADION.sql...
Loading file /tmp/HRF.sql...
Loading file /tmp/TA_FAVORITE.sql...
Loading file /tmp/SPIELERNOTIZ.sql...
Loading file /tmp/MATCHDETAILS.sql...
Loading file /tmp/VEREIN.sql...
Loading file /tmp/TRANSFERTYPE.sql...
Loading file /tmp/XTRADATA.sql...
Loading file /tmp/MODULE_CONFIGURATION.sql...
Loading file /tmp/TEAM.sql...
Loading file /tmp/TOURNAMENTDETAILS.sql...
Loading file /tmp/STAFF.sql...
Loading file /tmp/BASICS.sql...
Loading file /tmp/POSITIONEN.sql...
Loading file /tmp/MATCHLINEUPPENALTYTAKER.sql...
Loading file /tmp/MATCHHIGHLIGHTS.sql...
Loading file /tmp/SCOUT.sql...
Loading file /tmp/PAARUNG.sql...
Loading file /tmp/USERCONFIGURATION.sql...
Loading file /tmp/TA_PLAYER.sql...
Loading file /tmp/SPIELER.sql...
Loading file /tmp/MATCHORDER.sql...
Loading file /tmp/TRANSFER.sql...
Loading file /tmp/TRAINING.sql...
Loading file /tmp/MATCHLINEUPPLAYER.sql...
Loading file /tmp/MATCHLINEUP.sql...
Loading file /tmp/SPIELPLAN.sql...
Loading file /tmp/MATCHLINEUPTEAM.sql...
Loading file /tmp/FUTURETRAINING.sql...
Loading file /tmp/MATCHESKURZINFO.sql...

   #+end_src

   3 values are accepted by the =version= argument:

   - =3.0.0= :: targets HO 3.x database,
   - =4.0.0= :: targets HO 4.x database,
   - =current= :: re-imports data in a database with the same schema
     as the source database.


** Export

   A database can also be exported as an archive containing the insert
   for the different tables in the db:

   #+begin_src bash
$ ./bin/hodb-repair -d ~/tmp/database -x /tmp
...  possible errors ...
Database has been exported to /tmp/database-2020-06-13-143931.zip.
   #+end_src

* License

  Copyright © 2020 Sébastien Le Callonnec

  This project is licensed under the GNU Lesser General Public License v3.0.
